### PR TITLE
Complete Flow Re-design (per Jooize's direction)

### PR DESCRIPTION
**Pull request by proteanx**
Updated the site navigation according to flow chart presented by jooize. Will continue to make updates (including removing drop-downs). I just wanted to see how this flows first.

### CODE REVIEW

**Comment by jooize** [comment]
We need to preview these changes on a development server. Changes in URLs should not be done often, so we must think them through. I have a vision in progress, but not a finished one. Care is necessary to avoid external broken links. We'll have to redirect `nubits.com/exchanges/nubits-exchanges` to what we settle on. `nubits.com/about/jobs` should be moved and redirected to `nubits.com/jobs` (this one you can do right away!).

I don't want to change our slogan from “World's Best Stable Digital Currencies” to “The Digital Dollar Decentralized”. I think it is worse, and we will not provide only digital ‘dollars’.

Please do not make content changes. Those need to be made, but I intend to cut down a lot of the current material to the essentials. I'm aiming at reducing or preferably removing the FAQ. We need to figure out what information people is looking for, and provide it as succinctly we can. It seems I will be the one to rewrite them.

I want you to set up so I can view your changes before we push them to NuBits.com. Primarily work on the layout that I suggested, and be prepared to make changes to it. The amount of menu items will likely change. Ask me before you work on other things.

**Comment by inuitwallet** [comment]
@proteanx if you enable github pages from the settings of your fork of this repo, we can check the changes without affecting the live nubits.com site.
For example https://inuitwallet.github.io/nunetwork.github.io/ is hosted from my fork of the repo.

**Comment by jooize** [comment]
@inuitwallet Should that work immediately without modification? I got the warning “The CNAME www.nubits.com is already taken. Check out https://help.github.com/articles/troubleshooting-custom-domains/#cname-already-taken for more information.” and no graphics on mine.

**Comment by proteanx** [comment]
I'll setup the pages url so you guys can check it out. I have Jeckyll installed locally so I've been just viewing it locally.

**Pull request closed without merging**
